Algoritmo "medidas"

Var

   a ,b ,c , triangulo, trapezio , quadrado : real

Inicio

   escreva("Digite a medida A: ")
   leia(a)
   escreva("Digite a medida B: ")
   leia(b)
   escreva("Digite a medida C: ")
   leia(c)
   quadrado <- a^2
   triangulo <- a * b / 2
   trapezio <- (a + b) * c /2
   escreval("AREA DO QUADRADO = ", quadrado:2:4)
   escreval("AREA DO TRIANGULO = ", triangulo:2:4)
   escreva("AREA DO TRAPEZIO = ", trapezio:2:4)

Fimalgoritmo